#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-rpm-packaging
Version  : a18ca48959c95aefa725317084dd2d3e242e4f71
Release  : 1
URL      : https://github.com/rpm-software-management/python-rpm-packaging/archive/a18ca48959c95aefa725317084dd2d3e242e4f71.tar.gz
Source0  : https://github.com/rpm-software-management/python-rpm-packaging/archive/a18ca48959c95aefa725317084dd2d3e242e4f71.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: python-rpm-packaging-license = %{version}-%{release}
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
# python-rpm-packaging
## Running tests
Requirements:
- Python >= 3.8
- pip >= 20.0.1
- setuptools
- pytest
- pytest-xdist
- pyyaml
- wheel
- poetry (due to [bug](https://github.com/pypa/pip/issues/9701))

%package license
Summary: license components for the python-rpm-packaging package.
Group: Default

%description license
license components for the python-rpm-packaging package.


%prep
%setup -q -n python-rpm-packaging-a18ca48959c95aefa725317084dd2d3e242e4f71
cd %{_builddir}/python-rpm-packaging-a18ca48959c95aefa725317084dd2d3e242e4f71

%build
## build_prepend content
chmod +x ./scripts/*
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1631571566
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
make  %{?_smp_mflags}  || true


%install
export SOURCE_DATE_EPOCH=1631571566
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/python-rpm-packaging
cp %{_builddir}/python-rpm-packaging-a18ca48959c95aefa725317084dd2d3e242e4f71/COPYING %{buildroot}/usr/share/package-licenses/python-rpm-packaging/588760a9f446cebfc4b61485cd09cd768908337f
true
## install_append content
dest=%{buildroot}/usr/lib/rpm
mkdir -pv $dest/fileattrs
cp -av ./fileattrs/* $dest/fileattrs/
cp -av ./scripts/* $dest/
## install_append end

%files
%defattr(-,root,root,-)
/usr/lib/rpm/brp-python-bytecompile
/usr/lib/rpm/brp-python-hardlink
/usr/lib/rpm/fileattrs/python.attr
/usr/lib/rpm/fileattrs/pythondist.attr
/usr/lib/rpm/pythondistdeps.py

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/python-rpm-packaging/588760a9f446cebfc4b61485cd09cd768908337f
